### ISSUE TITLE
Ready yet?

### ISSUE THREAD

**Issue by doughsay** [vectordotdev/timber-node#22]
Hi there, I'm very interested to give this a shot.  Is this ready yet?  Your online docs don't have any instructions for node apps, and the readme here is a bit sparse...

**Comment by ariamckinley** [comment]
The current version is fairly basic, but it does transport logs to the timber service.

The only thing you have to do to get it running is run the two lines shown in the readme:

```js
const timber = require('timber');
timber.install({
  apiKey: 'your-api-key'
});
```

This will transport all logs outputted in stdout to your Timber app.

We're currently working hard on a new version that has support for express middleware (#21). Once this is released, the middleware will automatically append additional context data (i.e. http method, path, client ip, status code, execution time, etc) to your log lines before shipping to Timber.

Feel free to give it a shot in it's current state though, and definitely reach out if you have any questions or run into any issues; we're happy to help! 🌲

**Comment by binarylogic** [comment]
Hey Chris, also to clarify, [the branch](https://github.com/timberio/timber-node/tree/express-middleware-wip) @garetmckinley is working on will bring the node library up to date feature, documentation, and quality wise. We'll update the readme to match our other libraries, provide library documentation, as well as docs in the [Timber docs](https://timber.io/docs). I'd recommend waiting for that branch if you can, there are a number of improvements that will make the experience much better.

**Comment by doughsay** [comment]
Thanks guys, I'll definitely be keeping my eye out for that pull request.  As great as express based metadata will be, I'm also very curious about submitting custom (structured) events to timber from node.  I'm already doing this in elixir, and it's really helpful being able to search the logs using custom fields and such.  Will this also be possible soon?

Anyway, thanks for the updates!
