### ISSUE TITLE
Add `timestamp_prefix` to output configuraiton options

### ISSUE THREAD

**Issue by DavidAntaramian** [vectordotdev/timber-node#24]
Currently, when writing out to a file, I get output like:

```
Example app listening on port 3000! @metadata {"$schema":"https://raw.githubusercontent.com/timberio/log-event-json-schema/1.2.3/schema.json","message":"Example app listening on port 3000!\n","dt":"2017-06-26T16:51:47.997Z","level":"info"}
```

I need a `timestamp_prefix` option which is a boolean flag with default value of `false`.

When `true`, output should be prefixed with a timestamp in ISO 8601 format (with nanosecond precision if possible). The resulting output should look like this:

```
2017-06-26T16:44:06Z Example app listening on port 3000! @metadata {"$schema":"https://raw.githubusercontent.com/timberio/log-event-json-schema/1.2.3/schema.json","message":"Example app listening on port 3000!\n","dt":"2017-06-26T16:51:47.997Z","level":"info"}
```

**Comment by binarylogic** [comment]
I would add that the `dt` key in the metadata should also be removed.

**Comment by DavidAntaramian** [comment]
Updated to use the `Z` notation instead of the `-`/`+` offset notation
