### ISSUE TITLE
Support meta syntax for Winston

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/timber-node#35]
We support a root level `meta` key, which is an arbitrary map that is not classified as an event:

```
winston.log('info', 'Test Log Message', { key1: "val1", key2: {nestedKey: "nestedVal"} });
```

```
{"meta": {"key1": "val1", "key2": {"nestedKey": "nestedVal"} } }
```

**Comment by ariamckinley** [comment]
This is actually already done in #30 (https://github.com/timberio/timber-node/blob/winston-transport/src/transports/winston.js#L39-L42)

**Comment by binarylogic** [comment]
Cool, feel free close
