### ISSUE TITLE
Support metadata logging from the console

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/timber-node#41]
We do *not* want to modify the default behavior of `console`, but if arguments are logged in a very specific strict manner we can make assumptions. For example:

```js
console.log("Payment rejected", {meta: {key: "value", key2: "value2"}})
```

Conditions:

1. Only 2 arguments must be logged
2. The first must be a string.
3. The second must be an object.
4. The object must have a *single* root level key called `meta`
5. The `meta` value must be an object.

**Comment by ariamckinley** [comment]
@binarylogic should this work *only* for metadata? What about logging custom events and context using the same conditions, similar to how custom events can be logged in winston:

```js
console.log("Payment rejected", {event: {checkout: {error: "invalid ccv"}}});
```

**Comment by ariamckinley** [comment]
Ah nevermind, just realized you had a separate issue opened for event logging to console. Awesome, I'll add it in as well.
