### ISSUE TITLE
Update and organize README by logger type

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/timber-node#45]
This is blocked, I want to finalize our other library READMEs before embarking on this.

**Comment by ariamckinley** [comment]
Is this still blocked? The readme is now [broken up by logger type](https://github.com/timberio/timber-node#usage). Let me know if there's anything I can do to help with this

**Comment by ariamckinley** [comment]
Is this ready to be closed?

**Comment by binarylogic** [comment]
Yep yep
