### ISSUE TITLE
Update default Express HTTP logging

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/timber-node#47]
Correct me if I'm wrong, but based on what I've seen, the standard is to log a single line for the response. This is something new that we now support. Notice the `request` object [here](https://github.com/timberio/log-event-json-schema/blob/master/schema.json#L607). This is a sub-document of the response. I'd recommend we log a single `HTTPResponse` event with those request details filled out. The message format should follow the default morgan format: https://github.com/expressjs/morgan/blob/master/index.js#L164

IMO, each integration should be able to log it's own custom message. So instead of coupling the message with the object, it would be something like:

```
log('info', ':remote-addr - :remote-user [:date] ":method :url HTTP/:http-version" :status :res[content-length] ":referrer" ":user-agent"', http_response_event)
```

**Comment by binarylogic** [comment]
Noting that the `log` method above requires https://github.com/timberio/timber-node/issues/42

**Comment by ariamckinley** [comment]
@binarylogic  Just to make sure I'm understanding correctly: the logger should parse the message string looking for a pattern like `:parameter` and then replace it with the matching value from the event object?

Should it only parse the message if an event object is passed, or would this behavior be applicable for context objects as well?

**Comment by binarylogic** [comment]
Oh no, not at all. I didn't intend for there to be actual format / template string. I should have been more clear with that. I was saying the end result should be similar, but not exact. For example:

```
${method} ${path} ${status} in ${response_time}ms
```

Where these variables are actual variables that result in a string similar to:

```
GET /path 200 in 428ms
```

My goal with this is to ensure Timber does not stray from the expected / norm too far. You can say better than I can if that is the case here.

**Comment by ariamckinley** [comment]
Oh phew. This library is already doing that [here](https://github.com/timberio/timber-node/blob/winston-transport/src/events/http_response.js#L37). Are you just saying that the message should be customizable outside of the event class?

**Comment by ariamckinley** [comment]
Or are you just talking about combining both the [request](https://github.com/timberio/timber-node/blob/winston-transport/src/middlewares/express.js#L104) and [response](https://github.com/timberio/timber-node/blob/winston-transport/src/middlewares/express.js#L108) lines in the middleware?

**Comment by binarylogic** [comment]
I was saying we want our log messages and formats to feel familiar to anyone transitioning from the default express logging. The goal of Timber is not to change your original log messages, it's to augment them with metadata and context. So when they log into Timber it should feel somewhat familiar, then clicking the line reveals all of context.
