### ISSUE TITLE
Assertion error "stream" is not writable

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/timber-node#69]
We had a user report the following:

> Hey there! After following your steps at https://timber.io/docs/languages/node/installation/stdout for Bunyan I only receive AssertionErrors:
>
> AssertionError [ERR_ASSERTION]: "stream" stream is not writable: [Function: BunyanTransport]
>
> But after changing
>
> timber.transports.Bunyan;
>
> to
>
> timber.transports.BunyanTransport;
>
> everything works fine.
>
> Could there be a documentation issue or am I missing something?

**Comment by jarrodldavis** [comment]
I ran into this same issue and the problem is that the docs say:

```js
const log = bunyan.createLogger({
  name: 'Logger',
  stream: timber.transports.Bunyan
});
```

but it should be:

```js
const log = bunyan.createLogger({
  name: 'Logger',
  stream: new timber.transports.Bunyan()
});
```

because `timber.transports.Bunyan` is a class, not a stream instance.

Here's a diff:
```diff
--- actual.js	2017-11-04 12:12:05.000000000 -0500
+++ expected.js	2017-11-04 12:12:16.000000000 -0500
@@ -1,5 +1,5 @@
 const log = bunyan.createLogger({
   name: 'Logger',
-  stream: timber.transports.Bunyan
+  stream: new timber.transports.Bunyan()
 });
 
```

**Comment by binarylogic** [comment]
Thanks Jarrod, I'm updating the docs now.
