### ISSUE TITLE
Call stack exceeded when included.

### ISSUE THREAD

**Issue by Cristy94** [vectordotdev/timber-node#71]
I'm trying to include timber, but the app crashes. My code (I am using TS and Webpack):

```
import * as timber from 'timber';
console.log(timber);
```

Results in:

```
 RangeError: Maximum call stack size exceeded
     at String.slice (native)
    at normalizeStringWin32 (path.js:85:22)
   at Object.normalize (path.js:426:14)
   at Object.join (path.js:550:18)
...
webpack:\node_modules\find-package-json\index.js:49:1)
```

**Comment by Cristy94** [comment]
Is this project dead?

**Comment by zsherman** [comment]
hey @Cristy94, so this library is not actually meant for browsers but exclusively for server side node applications. We are working on a separate version of Timber specifically built for the front-end which we hope to release in the coming months.

**Comment by Cristy94** [comment]
? I am using it inside Node.js, not inside the browser, I did not mention anywhere I am using it inside the browser. I think the issue is that the `find-package-json` module fails because I currently have the app that has it's package.json inside another folder that itself has a package.json, not sure if this is the issue though. It's the only package that throws this error.

So, my setup looks like this:

```
app
  package.json
  utils
     timber.ts (where timber is included)
     package.json

```

And I am using webpack to bundle everything.

**Comment by zsherman** [comment]
Ok, I assumed since you're using webpack and TypeScript that you were bundling files for the browser. Having two `package.json`s might definitely be an issue, can I ask why you separated it out like that?

Is Timber installed in the root `package.json` or the one inside of utils?

**Comment by Cristy94** [comment]
@zsherman That happens when you have a micro-services architecture.

```
Main app
  package.json (shared packages by all microservices, so they all have the same versions)
  // timber is a dependency in this package
  chat app
      package.json
  login app
      package.json 
      // requiring timber here throws the error
```

So in this case you don't have to install the same package in all places and worry about their versions. 

I want to note that we use many other packages and all work as expected, but the timber package doesn't.
