### ISSUE TITLE
TypeError: Cannot read property 'timber' of undefined

### ISSUE THREAD

**Issue by Jbarget** [vectordotdev/timber-node#75]
I have a react app and following instructions when setting up a new Organisation and App:

i've run:
- `npm i -S timber`
- put `const timber = require("timber");`

in my entry file `index.js`, and i get the following error:

![screen shot 2018-03-05 at 15 12 49](https://user-images.githubusercontent.com/11725595/36982996-2a32b00a-2089-11e8-8295-2b77358cd196.png)

The app was created with `create-react-app` and have a feeling it could be to do with something because of that

any help would be great!

**Comment by zsherman** [comment]
Hey @Jbarget currently this package does not support browser environments, but it's certainly on our roadmap. Could you tell me a little bit more about how you'd like to configure your logging?

**Comment by Jbarget** [comment]
Gotcha :) 

For client side react projects I was hoping for it to be pretty much the same as the install instructions for node apps:

- npm i
- create new instance in initial script
- start using `console.error` etc...

Is there anything else that would be helpful to know?

**Comment by zsherman** [comment]
Gotcha thanks @Jbarget, I'm closing this in favor of #76 and will keep that updated as we go.
