### ISSUE TITLE
Cannot use attach in node

### ISSUE THREAD

**Issue by lorenzoridolfi** [vectordotdev/timber-node#77]
The example in the documentation for using attach doesn't work at https://timber.io/docs/languages/node/configuration/logging-to-multiple-streams/ 

Please provide me a working example.

**Comment by jsonmaur** [comment]
Hey @lorenzoridolfi, thanks for pointing this out! Looks like there were some syntax errors in the documentation's code example. I'll get that fixed right away. In the meantime, here's a working example of using `attach` with a basic express app:

```javascript
const fs = require('fs')
const timber = require('timber')
const express = require('express')

const http_stream = new timber.transports.HTTPS('{your_timber_api_key}')
const file_stream = fs.createWriteStream('./app_logs', {flags: 'a'})

timber.attach([http_stream, file_stream], process.stdout)
timber.attach([http_stream, file_stream], process.stderr)

const app = express()
app.use(timber.middlewares.express())

app.get('*', (req, res, next) => {
  res.send('hello world')
  next()
})

app.listen(8000, () => {
  console.log('server started')
})
```

Let me know if this works for you.
